# Archivo: .github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests con Jest
        run: npm run test
